name: CI

on: [push, pull_request]

jobs:
  cypress-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'  # ou a versão que você está usando

      - name: Install dependencies
        run: npm install

      - name: Start HTTP server
        run: npm run start-server &
        # Esse passo inicia o servidor HTTP em segundo plano

      - name: Wait for server to be ready
        run: sleep 10
        # Aguarda 10 segundos para garantir que o servidor HTTP esteja pronto

      - name: Run Cypress tests with Pixeleye
        run: npm run test

      - name: Archive screenshots and videos
        if: always()
        uses: actions/upload-artifact@v2
        with:
          name: cypress-artifacts
          path: |
            cypress/screenshots
            cypress/videos
